/**
 * This file is generated by generate-i18n.mjs
 * Do not edit this file directly
 */
import type enMessage from '../locales/en/messages.json';
import type jaMessage from '../locales/ja/messages.json';

export type MessageKey = keyof typeof enMessage & keyof typeof jaMessage;

export type DevLocale = 'en' | 'ja';
