[phases.setup]
nixPkgs = ['nodejs_22', 'pnpm-9_x']

[phases.install]
cmds = [
  'cd backend-service',
  'npm install'
]

[phases.build]
cmds = ['echo "No build step required"']

[start]
cmd = 'cd backend-service && npm start' 